spring.application.name=quantity-measurement-app
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_db
spring.datasource.username=root
spring.datasource.password=Mani230252@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
